### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MaanavT**

### CODE REVIEW

**Comment by Alby0n** [comment]
Name files appropriately for better understanding.

**Comment by MaanavT** [comment]
Have Renamed the files, please do check

regards
Maanav T

**Comment by 4k5h1t** [comment]
Follow C file naming conventions like :
File names are made up of a base name, and an optional period and suffix. The first character of the name should be a letter and all characters (except the period) should be lower-case letters and numbers. The base name should be eight or fewer characters .

**Comment by MaanavT** [comment]
Have renamed it , hope it is correct. please do check
Thank you
regards
Maanav T

**Comment by Alby0n** [comment]
good job 👍

**Pull request merged**
