### PR TITLE
transpose of a matrix.py

### PR DESCRIPTION
**Pull request by NEHA-MERIYA**

### CODE REVIEW

**Comment by 4k5h1t** [comment]
Needs the .py extension

**Comment by NEHA-MERIYA** [comment]
> Needs the .py extension

Updated it.

**Comment by 4k5h1t** [comment]
I meant the actual file name needs to have the extension, not the title of the pull request

**Review by 4k5h1t — CHANGES_REQUESTED** [review]
This file requires the .py extension to be seen as a python file, right now it is just a text file

**Review by 4k5h1t — APPROVED** [review]

**Comment by 4k5h1t** [comment]
Fixed the issue, looks good now :+1:

**Pull request merged**
