### PR TITLE
Hacktoberfest2022 participation

### PR DESCRIPTION
**Pull request by asifurrahmanpial**
updated airline registration extension

### CODE REVIEW

**Comment by 4k5h1t** [comment]
Not sure your file can run in it's current state. It doesn't have the '.cpp' extension after the file name.

**Comment by 4k5h1t** [comment]
The PROFILES.md file looks wrong, could you make sure it fits the format. The Github link isnt visible

**Comment by Alby0n** [comment]
resolve the conflicts

**Review by 4k5h1t — APPROVED** [review]

**Comment by 4k5h1t** [comment]
Looks Good

**Pull request merged**
