### PR TITLE
intersection of two list.py

### PR DESCRIPTION
**Pull request by NEHA-MERIYA**
this program computes the intersection of two given lists.

### CODE REVIEW

**Comment by 4k5h1t** [comment]
Again, needs .py extension

**Comment by NEHA-MERIYA** [comment]
> Again, needs .py extension

Updated it.

**Comment by 4k5h1t** [comment]
Two problems on this pr.
a) The file is still a text file, you need to rename the actual file to have the .py extension. (Check your previous PRs I have fixed some)
b) The file is not in the Python Programs Folder, need to move it

**Review by 4k5h1t — CHANGES_REQUESTED** [review]
Add .py extension to the file and move to Python Programs

**Pull request merged**
